### ISSUE TITLE
travis CI not using Python 3 as intended

### ISSUE THREAD

**Issue by lukashergt** [fruzsinaagocs/oscode#10]
As seen in #9, the travis CI is not actually using the Python versions that are requested in `.travis.yml`. It seems to ignore the `python` field completely and always uses the system Python, which typically is Python 2.7.

This becomes very clear with the commit [cb90a3d](https://github.com/fruzsinaagocs/oscode/pull/9/commits/cb90a3d06ea327fcbf06c02da238a4464c89c579) that makes travis print out the used python version. See for example the job [195.1](https://travis-ci.com/github/fruzsinaagocs/oscode/jobs/482860993), where it shows that Python 2.7.17 was used instead of the expected Python 3.7.

**Comment by fruzsinaagocs** [comment]
Thank you for spotting this! Please see the review of #9 (now merged) for the explanation of what happened. Fixed in d3bb2ce994fa41d91f08ea4a5a599c7db7d12e42.
