### ISSUE TITLE
Problems with dense output of the `Solution` class

### ISSUE THREAD

**Issue by sebhoof** [fruzsinaagocs/oscode#13]
I found an issue when instantiating the `Solution` class via e.g. passing a `std::vector<double>` to the `const X &do_times` variable (same for a list). The time ordering of the dense output class member lists is off, which is also reflected in the associated output file. Another issue is that a part of the solution (probably the parts obtained with the RK solver) seem to have been set to 0.

To reproduce this in a minimal example, I modified the `burst.cpp` file as follows (currently only non-dense output is included).

```
std::vector<double> temp;
for (int i = 0; i < 1000; ++i) { temp.push_back(-2*n + 4*n*i*0.001); }

de_system sys(&w, &g);
Solution solution(sys, x0, dx0, ti, tf, temp, 3, 1e-4, 0.0, 1, "native_do.dat");
solution.solve();

std::vector<double> do_ts(std::begin(solution.dotimes), std::end(solution.dotimes));
std::vector<std::complex<double> > do_xs(std::begin(solution.dosol), std::end(solution.dosol));

for (int i = 0; i < do_xs.size(); ++i)
{
     std::cout << temp[i] << " " << do_ts[i] << " " << do_xs[i] << std::endl;
}
```

Both the printed lines and the contents of `native_do.dat` should show the issues mentioned above.

**Comment by fruzsinaagocs** [comment]
Thank you for submitting an issue! The problem was that the direction of integration wasn't being set to 'forward' unless the frequency and friction terms `w, g` were provided as array-like objects. The linked PR fixes your example.
