### ISSUE TITLE
(even?) spacing of "time" array in pyoscode

### ISSUE THREAD

**Issue by lukashergt** [fruzsinaagocs/oscode#2]
### Does pyoscode assume that the grid of timepoints `ts` passed to `pyoscode.solve` is evenly spaced?

In the documentation it says for the C++ interface that 

> * For the sake of speed, oscode will assume the grid of timepoints \omega and \gamma are given on is evenly spaced. It is possible not to supply an evenly spaced grid, this will be discussed later.

The pyscode documentation does not specify this. There it only says (note also awkward splitting of word `independent`):

>     ts: numpy.ndarray [float] or list [float]
>         An array of real numbers representing the values of the independe
>         nt variable at which the frequency and friction term are evaluated. 

If it indeed is assuming `ts` to be evenly spaced, then it would probably be good to 
1) update the pyoscode documentation accordingly
2) check the `ts` input accordingly and raise an error or at least a warning if the condition is violated

---

Possibly nice features:
* allow uneven spacing of `ts`
* have option of log spacing of `ts`, i.e. for `np.logspace` time arrays as input

**Comment by fruzsinaagocs** [comment]
Hi,

Thanks for submitting an issue. 

> Does pyoscode assume that the grid of timepoints ts passed to pyoscode.solve is evenly spaced?

**Yes.** At the moment both the C++ and Python interface assumes that the input arrays for the independent variable are evenly spaced _by default_, to performs quick linear interpolation. However it is possible to define your own interpolation routine in the C++ interface, and relax the evenly-spaced arrays condition.

> Possibly nice features:
>
>    - allow uneven spacing of ts
>    - have option of log spacing of ts, i.e. for np.logspace time arrays as input

Both suggestions are good, and I'll aim to make these options available the near future. Flagged as feature request.

**Comment by fruzsinaagocs** [comment]
As of https://github.com/fruzsinaagocs/oscode/commit/c826ba52ccfd723c79f2f114c10ea66759d295da (v1.0.0 release), the `ts` grid need not be evenly spaced. `pyoscode.solve()` will assume it is not evenly spaced by default, unless `even_grid` is `True`. Giving an evenly sampled grid and setting `even_grid=True` will give a small speedup due to not needing to search for nearest neighbours in linear interpolation on this grid. Closing this issue.
