### ISSUE TITLE
Installation on windows 10

### ISSUE THREAD

**Issue by gubaomin** [fruzsinaagocs/oscode#20]
It seems that there is an error for the installation on windows 10. The error message is "Microsoft Visual C++ 14.0 or greater is required'. It fails to build wheels for pyoscode.

**Comment by fruzsinaagocs** [comment]
Hi @gubaomin, thank you for submitting this issue! I added windows-latest to the systems CI is done on and after some fixes it now passes. This should be Win 10, here are the details: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
