### ISSUE TITLE
How to include Eigen

### ISSUE THREAD

**Issue by lukashergt** [fruzsinaagocs/oscode#3]
I remember having had issues previously with installing pyoscode (`python setup.py install`) because of the error
```
pyoscode/_pyoscode.hpp:6:10: fatal error: Eigen/Dense: No such file or directory
```
and I'm running into this again now. 

I have Eigen on my system, but how do I let pyoscode know where it is? What would be the best way of handling this? Do I need to create symlinks as mentioned in Eigen's [Getting started](http://eigen.tuxfamily.org/dox/GettingStarted.html)?

**Comment by fruzsinaagocs** [comment]
Hi,

There are two ways of handling this:

1) As you said, you could follow Eigen's guide and set up symlinks,
2) You can also include the location of your Eigen library for the installation of (py)oscode, as described in the [FAQ](https://github.com/fruzsinaagocs/oscode#installation-1):

```bash 
CPLUS_INCLUDE_PATH=/usr/include/eigen3 python setup.py install --user
# or
CPLUS_INCLUDE_PATH=/usr/include/eigen3 pip install pyoscode
```

Hope this helps, feel free to respond if the issue persists.

**Comment by lukashergt** [comment]
```bash
CPLUS_INCLUDE_PATH=/usr/include/eigen3 pip install .
```

This is exactly what I needed. Thanks! Sorry I didn't see this in the FAQ. I think this would be good to have directly in the installation instructions, though.
